# confluent-platform with kafka, zookeeper, schema registry, and REST proxy
version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:3.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
  schema-registry:
    image: confluentinc/cp-schema-registry:3.0.1
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
  rest-proxy:
    image: confluentinc/cp-kafka-rest:3.0.1
    depends_on:
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "schema-registry:8081"
      KAFKA_REST_HOST_NAME: "rest-proxy"